### ISSUE TITLE
User-defined drag cursor reverts to default cursor when dragging

### ISSUE THREAD

**Issue by brietsparks** [kutlugsahin/react-smooth-dnd#25]
The drag handle cursor style appears on hover, but when dragging, it changes back to the default arrow cursor. Example: https://kutlugsahin.github.io/smooth-dnd-demo/

**Comment by kutlugsahin** [comment]
Hey @brietsparks it is fixed in version 0.5.1
Cheers!

**Comment by slutske22** [comment]
@kutlugsahin  I am still experiencing this.  Not sure if its because I'm using react 18 and MUI5, though I'm not sure why that should matter?
